module.exports = [
{
    destination: "London",
    start_date: "05/01/2023", 
    end_date: "05/08/2023",
    duration: 7, 
    traveler_name: "John Smith",
    traveler_age: 35, 	
    traveler_gender: "Male",	
    traveler_nationality: "American",
    accommodation_type: "Hotel",
    accommodation_cost: 1200,	
    transportation_type: "Flight",
    transportation_cost: 600
}, 
{
    destination: "Phuket, Thailand",
    start_date: "06/15/2023", 
    end_date: "6/20/2023",
    duration: 5, 
    traveler_name: "Jane Doe",
    traveler_age: 28,	
    traveler_gender: "Female",	
    traveler_nationality: "Canadian",
    accommodation_type: "Resort",
    accommodation_cost: 800,	
    transportation_type: "Flight",
    transportation_cost: 500
},
{
    destination: "Bali, Indonesia",
    start_date: "07/01/2023", 
    end_date: "07/08/2023",
    duration: 5, 
    traveler_name: "David Lee",
    traveler_age: 45,	
    traveler_gender: "Male",	
    traveler_nationality: "Korean",
    accommodation_type: "Villa",
    accommodation_cost: 1000,	
    transportation_type: "Flight",
    transportation_cost: 700
    
},
{
    destination: "New York, USA",
    start_date: "08/15/2023", 
    end_date: "08/29/2023",
    duration: 14, 
    traveler_name: "Sarah Johnson",
    traveler_age: 29,	
    traveler_gender: "Female",	
    traveler_nationality: "British",
    accommodation_type: "Hotel",
    accommodation_cost: 2000,	
    transportation_type: "Flight",
    transportation_cost: 1000
},
{
    destination: "Tokyo, Japan",
    start_date: "09/10/2023", 
    end_date: "09/17/2023",
    duration: 7, 
    traveler_name: "Kim Nguyen",
    traveler_age: 26,	
    traveler_gender: "Female",	
    traveler_nationality: "Vietnamese",
    accommodation_type: "Airbnb",
    accommodation_cost: 700,	
    transportation_type: "Train",
    transportation_cost: 200
},
{
    destination: "Paris, France,",
    start_date: "10/05/2023", 
    end_date: "10/10/2023",
    duration: 5, 
    traveler_name: "Michael Brown",
    traveler_age: 42,	
    traveler_gender: "Male",	
    traveler_nationality: "American",
    accommodation_type: "Hotel",
    accommodation_cost: 1500,	
    transportation_type: "Flight",
    transportation_cost: 800
},
{
    destination: "Sydney, Australia",
    start_date: "11/20/2023", 
    end_date: "11/30/2023",
    duration: 10, 
    traveler_name: "Emily Davis",
    traveler_age: 33,	
    traveler_gender: "Female",	
    traveler_nationality: "Australian",
    accommodation_type: "Hostel",
    accommodation_cost: 500,	
    transportation_type: "Flight",
    transportation_cost: 1200
},
{
    destination: "Rio de Janeiro, Brazil",
    start_date: "01/05/2024", 
    end_date: "01/12/2024",
    duration: 7, 
    traveler_name: "Lucas Santos",
    traveler_age: 25,	
    traveler_gender: "Male",	
    traveler_nationality: "Brazilian",
    accommodation_type: "Airbnb",
    accommodation_cost: 900,	
    transportation_type: "Flight",
    transportation_cost: 600
},
{
    destination: "Amsterdam, Netherlands",
    start_date: "02/14/2024", 
    end_date: "02/21/2024",
    duration: 7, 
    traveler_name: "Laura Janssen",
    traveler_age: 31,	
    traveler_gender: "Female",	
    traveler_nationality: "Dutch",
    accommodation_type: "Hotel",
    accommodation_cost: 1200,	
    transportation_type: "Train",
    transportation_cost: 200
},
{
    destination: "Dubai, United Arab Emirates",
    start_date: "03/10/2024", 
    end_date: "03/17/2024",
    duration: 7, 
    traveler_name: "Mohammed Ali",
    traveler_age: 39,	
    traveler_gender: "Male",	
    traveler_nationality: "Emirati",
    accommodation_type: "Resort",
    accommodation_cost: 2500,	
    transportation_type: "Flight",
    transportation_cost: 800
},
{
    destination: "Cancun, Mexico",
    start_date: "04/01/2024", 
    end_date: "04/08/2024",
    duration: 7, 
    traveler_name: "Ana Hernandez",
    traveler_age: 27,	
    traveler_gender: "Female",	
    traveler_nationality: "Mexican",
    accommodation_type: "Hotel",
    accommodation_cost: 1000,	
    transportation_type: "Flight",
    transportation_cost: 500
},
{
    destination: "Barcelona, Spain",
    start_date: "05/05/2024", 
    end_date: "05/22/2024",
    duration: 7, 
    traveler_name: "Carlos Garcia",
    traveler_age: 36,	
    traveler_gender: "Male",	
    traveler_nationality: "Spanish",
    accommodation_type: "Airbnb",
    accommodation_cost: 800,	
    transportation_type: "Train",
    transportation_cost: 100
},
{   
    destination: "Honolulu, Hawaii",
    start_date: "06/10/2024", 
    end_date: "06/18/2024",
    duration: 8, 
    traveler_name: "Lily Wong",
    traveler_age: 29,	
    traveler_gender: "Female",	
    traveler_nationality: "Chinese",
    accommodation_type: "Resort",
    accommodation_cost: 3000,	
    transportation_type: "Flight",
    transportation_cost: 1200
},

{
    destination: "Berlin, Germany",
    start_date: "07/01/2024", 
    end_date: "07/10/2024",
    duration: 9, 
    traveler_name: "Hans Mueller",
    traveler_age: 48,	
    traveler_gender: "Male",	
    traveler_nationality: "German",
    accommodation_type: "Hotel",
    accommodation_cost: 1400,	
    transportation_type: "Flight",
    transportation_cost: 700
},
{
    destination: "Marrakech, Morocco",
    start_date: "08/20/2024", 
    end_date: "08/27/2024",
    duration: 7, 
    traveler_name: "Fatima Khouri",
    traveler_age: 26,	
    traveler_gender: "Female",	
    traveler_nationality: "Moroccan",
    accommodation_type: "Riad",
    accommodation_cost: 600,	
    transportation_type: "Flight",
    transportation_cost: 400
},
{
    destination: "Edinburgh, Scotland",
    start_date: "09/05/2024", 
    end_date: "09/12/2024",
    duration: 7, 
    traveler_name: "James MacKenzie",
    traveler_age: 32,	
    traveler_gender: "Male",	
    traveler_nationality: "Scottish",
    accommodation_type: "Hotel",
    accommodation_cost: 900,	
    transportation_type: "Train",
    transportation_cost: 150
},
{
    destination: "Paris",
    start_date: "09/01/2023,", 
    end_date: "09/10/2023",
    duration: 9, 
    traveler_name: "Sarah Johnson",
    taveler_age: 30,	
    traveler_gender: "Female",	
    traveler_nationality: "American",
    accommodation_type: "Hotel",
    accommodation_cost: 900,	
    transportation_type: "Plane",
    transportation_cost: 400
},
{
    destination: "Bali",
    start_date: "08/15/2023,", 
    end_date: "08/25/2023",
    duration: 10, 
    traveler_name: "Michael Chang",
    traveler_age: 28,	
    traveler_gender: "Male",	
    traveler_nationality: "Chinese",
    accommodation_type: "Resort",
    accommodation_cost: 1500,	
    transportation_type: "Plane",
    transportation_cost: 700
},
{
    destination: "London",
    start_date: "07/22/2023", 
    end_date: "07/28/2023",
    duration: 6, 
    traveler_name: "Olivia Rodriquez",
    traveler_age: 35,	
    traveler_gender: "Female",	
    traveler_nationality: "British",
    accommodation_type: "Hotel",
    accommodation_cost: 1200,	
    transportation_type: "Train",
    transportation_cost: 150
},
{
    destination: "Tokyo",
    start_date: "10/05/2023", 
    end_date: "10/15/2023",
    duration: 10, 
    traveler_name: "Kenji Nakamura",
    traveler_age: 45,	
    traveler_gender: "Male",	
    traveler_nationality: "Japanese",
    accommodation_type: "Hotel",
    accommodation_cost: 1200,	
    transportation_type: "Plane",
    transportation_cost: 800
},
{
    destination: "New York",
    start_date: "11/20/2023", 
    end_date: "11/25/2023",
    duration: 5, 
    traveler_name: "Emily Lee",
    traveler_age: 27,	
    traveler_gender: "Female",	
    traveler_nationality: "American",
    accommodation_type: "Airbnb",
    accommodation_cost: 600,	
    transportation_type: "Bus",
    transportation_cost: 100
},
{
    destination: "Sydney",
    start_date: "12/05/2023", 
    end_date: "12/12/2023",
    duration: 7, 
    traveler_name: "James Wilson",
    traveler_age: 32,	
    traveler_gender: "Male",	
    traveler_nationality: "Australian",
    accommodation_type: "Hotel",
    accommodation_cost: 1000,	
    transportation_type: "Plane",
    transportation_cost: 600
},
{
    destination: "Rome",
    start_date: "11/01/2023", 
    end_date: "11/08/2023",
    duration: 7, 
    traveler_name: "Sofia Russo",
    traveler_age: 29,	
    traveler_gender: "Female",	
    traveler_nationality: "Italian",
    accommodation_type: "Airbnb",
    accommodation_cost: 700,	
    transportation_type: "Train",
    transportation_cost: 80
},
{
    destination: "Bangkok",
    start_date: "09/15/2023", 
    end_date: "09/23/2023",
    duration: 8, 
    traveler_name: "Raj Patel",
    traveler_age: 40,	
    traveler_gender: "Male",	
    traveler_nationality: "Indian",
    accommodation_type: "Hostel",
    accommodation_cost: 400,	
    transportation_type: "Plane",
    transportation_cost: 500
},

{
    destination: "Paris",
    start_date: "12/22/2023", 
    end_date: "12/28/2023",
    duration: 6, 
    traveler_name: "Lily Nguyen",
    traveler_age: 24,	
    traveler_gender: "Female",	
    traveler_nationality: "Vietnamese",
    accommodation_type: "Hotel",
    accommodation_cost: 1400,	
    transportation_type: "Train",
    transportation_cost: 100
},
{
    destination: "Hawaii",
    start_date: "08/01/2023", 
    end_date: "08/10/2023",
    duration: 9, 
    traveler_name: "David Kim",
    traveler_age: 34,	
    traveler_gender: "Male",	
    traveler_nationality: "Korean",
    accommodation_type: "Resort",
    accommodation_cost: 2000,	
    transportation_type: "Plane",
    transportation_cost: 800
},
{
    destination: "Barcelona",
    start_date: "10/20/2023,", 
    end_date: "10/28/2023",
    duration: 8, 
    traveler_name: "Marcia Garcia",
    traveler_age: 31,	
    traveler_gender: "Female",	
    traveler_nationality: "Spanish",
    accommodation_type: "Hotel",
    accommodation_cost: 1100,	
    transportation_type: "Train",
    transportation_cost: 150
},
{
    destination: "Japan",
    start_date: "05/10/2022", 
    end_date: "5/18/2022",
    duration: 8, 
    traveler_name: "Alice Smith",
    traveler_age: 30,	
    traveler_gender: "Female",	
    traveler_nationality: "American",
    accommodation_type: "Hotel",
    accommodation_cost: 800,	
    transportation_type: "Plane",
    transportation_cost: 500
},
{
    destination: "Thailand",
    start_date: "06/15/2022", 
    end_date: "06/22/2022",
    duration: 7, 
    traveler_name: "Bob Johnson",
    traveler_age: 45,	
    traveler_gender: "Male",	
    traveler_nationality: "Canadian",
    accommodation_type: "Hostel",
    accommodation_cost: 200,	
    transportation_type: "Train",
    transportation_cost: 150
},
{
    destination: "France",
    start_date: "07/02/2022", 
    end_date: "07/11/2022",
    duration: 9, 
    traveler_name: "Charlie Lee",
    traveler_age: 25,	
    traveler_gender: "Male",	
    traveler_nationality: "Korean",
    accommodation_type: "Airbnb",
    accommodation_cost: 600,	
    transportation_type: "Car rental",
    transportation_cost: 300
},
{
    destination: "Australia",
    start_date: "08/20/2022", 
    end_date: "09/02/2022",
    duration: 13, 
    traveler_name: "Emma Davis",
    traveler_age: 28,	
    traveler_gender: "Female",	
    traveler_nationality: "British",
    accommodation_type: "Hotel",
    accommodation_cost: 1000,	
    transportation_type: "Car rental",
    transportation_cost: 500
}
				
]										
	