module.exports = [
{
    Destination: "London, Uk",
    Start_date: "05/01/2023", 
    End_date: "05/08/2023",
    Duration: 7, 
    Traveler_name: "John Smith",
    Traveler_age: 35, 	
    Traveler_gender: "Male",	
    Traveler_nationality: "American",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1200,	
    Transportation_type: "Flight",
    Transportation_cost: 600
}, 
{
    Destination: "Phuket, Thailand",
    Start_date: "06/15/2023", 
    End_date: "6/20/2023",
    Duration: 5, 
    Traveler_name: "Jane Doe",
    Traveler_age: 28,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Canadian",
    Accommodation_type: "Resort",
    Accommodation_cost: 800,	
    Transportation_type: "Flight",
    Transportation_cost: 500
},
{
    Destination: "Bali, Indonesia",
    Start_date: "07/01/2023", 
    End_date: "07/08/2023",
    Duration: 5, 
    Traveler_name: "David Lee",
    Traveler_age: 45,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Korean",
    Accommodation_type: "Villa",
    Accommodation_cost: 1000,	
    Transportation_type: "Flight",
    Transportation_cost: 700
    
},
{
    Destination: "New York, USA",
    Start_date: "08/15/2023", 
    End_date: "08/29/2023",
    Duration: 14, 
    Traveler_name: "Sarah Johnson",
    Traveler_age: 29,	
    Traveler_gender: "Female",	
    Traveler_nationality: "British",
    Accommodation_type: "Hotel",
    Accommodation_cost: 2000,	
    Transportation_type: "Flight",
    Transportation_cost: 1000
},
{
    Destination: "Tokyo, Japan",
    Start_date: "09/10/2023", 
    End_date: "09/17/2023",
    Duration: 7, 
    Traveler_name: "Kim Nguyen",
    Traveler_age: 26,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Vietnamese",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 700,	
    Transportation_type: "Train",
    Transportation_cost: 200
},
{
    Destination: "Paris, France,",
    Start_date: "10/05/2023", 
    End_date: "10/10/2023",
    Duration: 5, 
    Traveler_name: "Michael Brown",
    Traveler_age: 42,	
    Traveler_gender: "Male",	
    Traveler_nationality: "American",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1500,	
    Transportation_type: "Flight",
    Transportation_cost: 800
},
{
    Destination: "Sydney, Australia",
    Start_date: "11/20/2023", 
    End_date: "11/30/2023",
    Duration: 10, 
    Traveler_name: "Emily Davis",
    Traveler_age: 33,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Australian",
    Accommodation_type: "Hostel",
    Accommodation_cost: 500,	
    Transportation_type: "Flight",
    Transportation_cost: 1200
},
{
    Destination: "Rio de Janeiro, Brazil",
    Start_date: "01/05/2024", 
    End_date: "01/12/2024",
    Duration: 7, 
    Traveler_name: "Lucas Santos",
    Traveler_age: 25,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Brazilian",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 900,	
    Transportation_type: "Flight",
    Transportation_cost: 600
},
{
    Destination: "Amsterdam, Netherlands",
    Start_date: "02/14/2024", 
    End_date: "02/21/2024",
    Duration: 7, 
    Traveler_name: "Laura Janssen",
    Traveler_age: 31,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Dutch",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1200,	
    Transportation_type: "Train",
    Transportation_cost: 200
},
{
    Destination: "Dubai, United Arab Emirates",
    Start_date: "03/10/2024", 
    End_date: "03/17/2024",
    Duration: 7, 
    Traveler_name: "Mohammed Ali",
    Traveler_age: 39,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Emirati",
    Accommodation_type: "Resort",
    Accommodation_cost: 2500,	
    Transportation_type: "Flight",
    Transportation_cost: 800
},
{
    Destination: "Cancun, Mexico",
    Start_date: "04/01/2024", 
    End_date: "04/08/2024",
    Duration: 7, 
    Traveler_name: "Ana Hernandez",
    Traveler_age: 27,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Mexican",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1000,	
    Transportation_type: "Flight",
    Transportation_cost: 500
},
{
    Destination: "Barcelona, Spain",
    Start_date: "05/05/2024", 
    End_date: "05/22/2024",
    Duration: 7, 
    Traveler_name: "Carlos Garcia",
    Traveler_age: 36,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Spanish",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 800,	
    Transportation_type: "Train",
    Transportation_cost: 100
},
{ Destination: "Honolulu, Hawaii",
    Start_date: "06/10/2024", 
    End_date: "06/18/2024",
    Duration: 8, 
    Traveler_name: "Lily Wong",
    Traveler_age: 29,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Chinese",
    Accommodation_type: "Resort",
    Accommodation_cost: 3000,	
    Transportation_type: "Flight",
    Transportation_cost: 1200
},

{
    Destination: "Berlin, Germany",
    Start_date: "07/01/2024", 
    End_date: "07/10/2024",
    Duration: 9, 
    Traveler_name: "Hans Mueller",
    Traveler_age: 48,	
    Traveler_gender: "Male",	
    Traveler_nationality: "German",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1400,	
    Transportation_type: "Flight",
    Transportation_cost: 700
},
{
    Destination: "Marrakech, Morocco",
    Start_date: "08/20/2024", 
    End_date: "08/27/2024",
    Duration: 7, 
    Traveler_name: "Fatima Khouri",
    Traveler_age: 26,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Moroccan",
    Accommodation_type: "Riad",
    Accommodation_cost: 600,	
    Transportation_type: "Flight",
    Transportation_cost: 400
},
{
    Destination: "Edinburgh, Scotland",
    Start_date: "09/05/2024", 
    End_date: "09/12/2024",
    Duration: 7, 
    Traveler_name: "James MacKenzie",
    Traveler_age: 32,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Scottish",
    Accommodation_type: "Hotel",
    Accommodation_cost: 900,	
    Transportation_type: "Train",
    Transportation_cost: 150
},
{
    Destination: "Paris",
    Start_date: "09/01/2023,", 
    End_date: "09/10/2023",
    Duration: 9, 
    Traveler_name: "Sarah Johnson",
    Traveler_age: 30,	
    Traveler_gender: "Female",	
    Traveler_nationality: "American",
    Accommodation_type: "Hotel",
    Accommodation_cost: 900,	
    Transportation_type: "Plane",
    Transportation_cost: 400
},
{
    Destination: "Bali",
    Start_date: "08/15/2023,", 
    End_date: "08/25/2023",
    Duration: 10, 
    Traveler_name: "Michael Chang",
    Traveler_age: 28,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Chinese",
    Accommodation_type: "Resort",
    Accommodation_cost: 1500,	
    Transportation_type: "Plane",
    Transportation_cost: 700
},
{
    Destination: "London",
    Start_date: "07/22/2023", 
    End_date: "07/28/2023",
    Duration: 6, 
    Traveler_name: "Olivia Rodriquez",
    Traveler_age: 35,	
    Traveler_gender: "Female",	
    Traveler_nationality: "British",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1200,	
    Transportation_type: "Train",
    Transportation_cost: 150
},
{
    Destination: "Tokyo",
    Start_date: "10/05/2023", 
    End_date: "10/15/2023",
    Duration: 10, 
    Traveler_name: "Kenji Nakamura",
    Traveler_age: 45,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Japanese",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1200,	
    Transportation_type: "Plane",
    Transportation_cost: 800
},
{
    Destination: "New York",
    Start_date: "11/20/2023", 
    End_date: "11/25/2023",
    Duration: 5, 
    Traveler_name: "Emily Lee",
    Traveler_age: 27,	
    Traveler_gender: "Female",	
    Traveler_nationality: "American",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 600,	
    Transportation_type: "Bus",
    Transportation_cost: 100
},
{
    Destination: "Sydney",
    Start_date: "12/05/2023", 
    End_date: "12/12/2023",
    Duration: 7, 
    Traveler_name: "James Wilson",
    Traveler_age: 32,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Australian",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1000,	
    Transportation_type: "Plane",
    Transportation_cost: 600
},
{
    Destination: "Rome",
    Start_date: "11/01/2023", 
    End_date: "11/08/2023",
    Duration: 7, 
    Traveler_name: "Sofia Russo",
    Traveler_age: 29,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Italian",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 700,	
    Transportation_type: "Train",
    Transportation_cost: 80
},
{
    Destination: "Bangkok",
    Start_date: "09/15/2023", 
    End_date: "09/23/2023",
    Duration: 8, 
    Traveler_name: "Raj Patel",
    Traveler_age: 40,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Indian",
    Accommodation_type: "Hostel",
    Accommodation_cost: 400,	
    Transportation_type: "Plane",
    Transportation_cost: 500
},

{
    Destination: "Paris",
    Start_date: "12/22/2023", 
    End_date: "12/28/2023",
    Duration: 6, 
    Traveler_name: "Lily Nguyen",
    Traveler_age: 24,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Vietnamese",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1400,	
    Transportation_type: "Train",
    Transportation_cost: 100
},
{
    Destination: "Hawaii",
    Start_date: "08/01/2023", 
    End_date: "08/10/2023",
    Duration: 9, 
    Traveler_name: "David Kim",
    Traveler_age: 34,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Korean",
    Accommodation_type: "Resort",
    Accommodation_cost: 2000,	
    Transportation_type: "Plane",
    Transportation_cost: 800
},
{
    Destination: "Barcelona",
    Start_date: "10/20/2023,", 
    End_date: "10/28/2023",
    Duration: 8, 
    Traveler_name: "Marcia Garcia",
    Traveler_age: 31,	
    Traveler_gender: "Female",	
    Traveler_nationality: "Spanish",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1100,	
    Transportation_type: "Train",
    Transportation_cost: 150
},
{
    Destination: "Japan",
    Start_date: "05/10/2022", 
    End_date: "5/18/2022",
    Duration: 8, 
    Traveler_name: "Alice Smith",
    Traveler_age: 30,	
    Traveler_gender: "Female",	
    Traveler_nationality: "American",
    Accommodation_type: "Hotel",
    Accommodation_cost: 800,	
    Transportation_type: "Plane",
    Transportation_cost: 500
},
{
    Destination: "Thailand",
    Start_date: "06/15/2022", 
    End_date: "06/22/2022",
    Duration: 7, 
    Traveler_name: "Bob Johnson",
    Traveler_age: 45,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Canadian",
    Accommodation_type: "Hostel",
    Accommodation_cost: 200,	
    Transportation_type: "Train",
    Transportation_cost: 150
},
{
    Destination: "France",
    Start_date: "07/02/2022", 
    End_date: "07/11/2022",
    Duration: 9, 
    Traveler_name: "Charlie Lee",
    Traveler_age: 25,	
    Traveler_gender: "Male",	
    Traveler_nationality: "Korean",
    Accommodation_type: "Airbnb",
    Accommodation_cost: 600,	
    Transportation_type: "Car rental",
    Transportation_cost: 300
},
{
    Destination: "Australia",
    Start_date: "08/20/2022", 
    End_date: "09/02/2022",
    Duration: 13, 
    Traveler_name: "Emma Davis",
    Traveler_age: 28,	
    Traveler_gender: "Female",	
    Traveler_nationality: "British",
    Accommodation_type: "Hotel",
    Accommodation_cost: 1000,	
    Transportation_type: "Car rental",
    Transportation_cost: 500
}
				
]										
	